version: "3"
services:
  # zookeeper docker image for Kafka sync & mgmt
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  # kafka docker image to set up single partition
  #   - also creates KafkaConnectivityTest topic for testing SDK connections
  kafka:
    image: "wurstmeister/kafka:latest"
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=KafkaConnectivityTest:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  # rust microservice to integrate with Kafka (producer)
  #   - don't really know what it does yet
  rust-kafka-producer:
    build:
      context: rust-kafka-producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust-kafka-producer/src:/app/src
  # rust microservice to consume Kafka info
  #   - might use this as the Email service
  rust-kafka-consumer:
    build:
      context: rust-kafka-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust-kafka-consumer/src:/app/src
  # nodejs gateway for auth and message issuance
  #   - need to architect what exactly this service does
  gateway:
    build:
      context: node-gateway
      dockerfile: Dockerfile
    hostname: gateway
    depends_on:
      - kafka
    volumes:
      - ./node-gateway/src:/app/src
      - ./node-gateway/node_modules:/app/node_modules
  # react front end client & wasm modules
  react-client:
    stdin_open: true
    image: react-client
    build:
      context: react-client
      dockerfile: Dockerfile
    volumes:
      - ./react-client/javascript/src:/app/javascript/src
      - ./react-client/javascript/node_modules:/app/javascript/node_modules
      - ./react-client/wasm/src:/app/wasm/src
      - ./react-client/wasm-build:/app/wasm-build
    depends_on:
      - wasm-base
  # wasm build base file
  #   - image includes a Node + WASM build + run environment + live reload
  wasm-base:
    image: wasm-base
    build:
      context: react-client/wasm
      dockerfile: Dockerfile
    volumes:
      - ./react-client/wasm/src:/app/wasm/src
  # gateway to proxy requests to both the client & node gateway
  nginx-gateway:
    restart: always
    depends_on:
      - react-client
      - gateway
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:80"
