version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:latest"
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=KafkaConnectivityTest:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  rust-kafka-producer:
    build:
      context: rust-kafka-producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust-kafka-producer/src:/app/src
  rust-kafka-consumer:
    build:
      context: rust-kafka-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust-kafka-consumer/src:/app/src
  node-gateway:
    build:
      context: node-gateway
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./node-gateway/src:/app/src
      - ./node-gateway/node_modules:/app/node_modules
  react-client:
    stdin_open: true
    build:
      context: react-client
      dockerfile: Dockerfile
    volumes:
      - ./react-client/src:/app/src
      - ./react-client/node_modules:/app/node_modules
      - ./react-client/wasm:/app/wasm
    depends_on:
      - wasm-base
  wasm-base:
    image: wasm-base
    build:
      context: react-client/wasm
      dockerfile: Dockerfile
    volumes:
      - ./react-client/wasm:/app/wasm
  nginx-gateway:
    restart: always
    depends_on:
      - react-client
      - node-gateway
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:80"
