version: "3"
services:
  # go-service:
  #   build:
  #     context: go
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #     - zookeeper
  zookeeper:
    image: "bitnami/zookeeper:latest"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rust-kafka:
    build:
      context: rust
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust/src:/app/src
