version: "3"
services:
  # go-service:
  #   build:
  #     context: go
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #     - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:latest"
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=KafkaConnectivityTest:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    links:
      - zookeeper
    ports:
      - "9092:9092"
  rust-kafka:
    build:
      context: rust
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust/src:/app/src
    links:
      - kafka
  rust-kafka-consumer:
    build:
      context: rust-kafka-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./rust-kafka-consumer/src:/app/src
    links:
      - kafka
